spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # could be hardcoded, but using env variables are better to not expose credentials
    username: postgres
    password: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
 